### ISSUE TITLE
"Go" button hangs over page edge on mobile

### ISSUE THREAD

**Issue by erickpeirson** [cul-it/arxiv-search#101]
![image](https://user-images.githubusercontent.com/3451594/37213873-5087c3a8-2381-11e8-9c8c-a6adafb8ddb3.png)

**Comment by erickpeirson** [comment]
Can I also submit an issue for Android's terrible clipboard support

**Comment by eawoods** [comment]
* note to self: check this after newest version of base is applied to arxiv.org/search-beta (footer styling is telling me that recent updates have not yet been applied).

**Comment by eawoods** [comment]
New layout to be implemented by [ARXIVNG-337](https://culibrary.atlassian.net/browse/ARXIVNG-337):
![screen shot 2018-03-12 at 2 33 38 pm](https://user-images.githubusercontent.com/17456668/37302622-6c3aa48e-2602-11e8-967d-8bc62300a608.png)

**Comment by erickpeirson** [comment]
Oh, that's gorgeous

**Comment by erickpeirson** [comment]
Nice fix for the pagination button alignment, too

**Comment by eawoods** [comment]
Thanks for noticing! It was an opportunistic fix.
