### ISSUE TITLE
Disabling search box in arXiv header when on search views?

### ISSUE THREAD

**Issue by erickpeirson** [cul-it/arxiv-search#142]
Should we do this? Would be easy to implement; define a flag in arXiv-base header template, and then set its value in the rendering context in the search views.

**Comment by eawoods** [comment]
For accessibility reasons, consistency is considered tantamount. This is worth a design consideration in the future, but mostly to design a header that looks good on all pages and is also consistent across all pages.

**Comment by erickpeirson** [comment]
Looks like we will not do this for now; we updated the running header to match fields available in simple search
