### ISSUE TITLE
Unicode for Abstract in search results?

### ISSUE THREAD

**Issue by rcplane** [cul-it/arxiv-search#161]
![screen shot 2018-04-17 at 12 47 06 pm](https://user-images.githubusercontent.com/1978942/38884493-cd0b960e-423d-11e8-9240-2382b441e417.png)

Is this expected or should this display as Gödel ?

**Comment by rcplane** [comment]
Also MathJax ?
![screen shot 2018-04-17 at 1 03 26 pm](https://user-images.githubusercontent.com/1978942/38885107-c839ab5a-423f-11e8-876c-a9f491ecf8de.png)

https://arxiv.org/search/?query=eess&searchtype=all&order=-announced_date_first&size=50

**Comment by erickpeirson** [comment]
This should now be fixed in develop, will be included in v0.2
![image](https://user-images.githubusercontent.com/3451594/39577445-5c798a62-4eaf-11e8-9815-98a311ede3a2.png)

**Comment by erickpeirson** [comment]
![image](https://user-images.githubusercontent.com/3451594/39577494-82078a54-4eaf-11e8-958e-50efa663e3cc.png)

**Comment by erickpeirson** [comment]
(although it looks like not all of the equations in that example are valid)
