### ISSUE TITLE
Mainpage "Find" links point to new search

### ISSUE THREAD

**Issue by rcplane** [cul-it/arxiv-search#162]
Currently it points as below; there is the deprecation warning but "Do Search" refuses to connect in Chrome (network console not showing more). 

https://arxiv.org/
https://arxiv.org/find/quant-ph
http://search.arxiv.org:8081/?query=blast&in=grp_physics

**Comment by erickpeirson** [comment]
Unfortunately we don't control that system. @mhl10 worth reaching out?

**Comment by rcplane** [comment]
![screen shot 2018-04-17 at 1 11 18 pm](https://user-images.githubusercontent.com/1978942/38885426-da1e3466-4240-11e8-8506-733f31db288f.png)

**Comment by mhl10** [comment]
@rcplane @erickpeirson I'll reach out

**Comment by erickpeirson** [comment]
Looks like their service is up; closing for now, can reopen if we have additional problems

**Comment by flckv** [comment]
![image](https://github.com/arXiv/arxiv-search/assets/103381497/838f0b6f-08ef-4ac5-8baa-2bba91834035)
 not working
