### ISSUE TITLE
Consider surname/forename approach from internationalization and multiple surname angles

### ISSUE THREAD

**Issue by eawoods** [cul-it/arxiv-search#38]
I recognize that this is a brand new and quickly implemented function! Props on getting it working in part. Some observations on names and the breakup into sur/fore in particular, to start a list of things to work out in the author search functionality.

Examples:

Chaimae El Aisati is broken into surname= Chaimae El forename=Aisati. Searching for any fragment of these doesn't work (C / Aisati, Chaimae El / A) but searching for forename Chaimae El and surname Aisati does. Other examples: P. Vasquez Regueiro, M. Vieites Diaz.

Double initials: R/Appleby does not return results, but R. B./Appleby does.

Organizations: some break on the last word (example: for the IceCube / Collaboration), some don't have a forename at all (example: / LHCb collaboration)

International: for Asian names that have forename/surname flipped, how do we know which is which? Can/should we search both sur- and forename fields for a string given as a name or name stem? We can then filter by relevance (and later facet by whole name, possibly). Also relevant for other cultures, or for the treatment of organization names in the author field.

Using a partial surname doesn't work, nor does using a wildcard.

**Comment by erickpeirson** [comment]
For 0.1: 

- Offer optional full-name search (parallel to forename/surname). 
- Include owner-authors in all author queries
- Add help text explaining the limitations and options around author search.

**Comment by erickpeirson** [comment]
ARXIVNG-308 - Offer optional full-name search (parallel to forename/surname)
ARXIVNG-309 - Include owner-authors in all author queries
ARXIVNG-310 - Add help text explaining the limitations and options around author search.
