### ISSUE TITLE
Author search page - validation error does not clear

### ISSUE THREAD

**Issue by eawoods** [cul-it/arxiv-search#42]
When a validation error has occurred (example: forename without surname), error conditions persist after user attempts to correct error.

Also, my browser (OS X El Capitan, Chrome 63.0) puts up an odd little icon to the right of forename once an error has occurred. No tooltips to say what this is, might be LastPass related? Or my individual browser addon settings? See screenshots. Error condition also propagates to additional field.

![screen shot 2018-02-05 at 1 54 44 pm](https://user-images.githubusercontent.com/17456668/35823170-9816f310-0a7c-11e8-806b-0aadbf8c795e.png)

![screen shot 2018-02-05 at 2 00 23 pm](https://user-images.githubusercontent.com/17456668/35823308-1adb4a62-0a7d-11e8-893a-832e24dd7fed.png)

**Comment by erickpeirson** [comment]
Has the user re-submitted the form? Or have they just begun typing in the box?

This is one of the HTML-rendering versus JS-responsive thresholds -- so far error handling/validation is all in the controller/form, so it won't clear until the form is resubmitted. We can go down the JS-responsive road, but wanted to start with something simple.

**Comment by eawoods** [comment]
I clicked the Back button instead of clicking on the query.  It's non-obvious that one can rewrite the query by clicking on the query - I'll assign that to myself as a UI problem rather than a code problem.

**Comment by eawoods** [comment]
When one clicks Back, the full correction (Cart) remains but the error doesn't clear.

**Comment by erickpeirson** [comment]
Ooo... that is weird. Wonder if it's the browser caching the page.

**Comment by erickpeirson** [comment]
Works as expected.
