### ISSUE TITLE
Collapse authors when more than 10 names, especially for mobile

### ISSUE THREAD

**Issue by eawoods** [cul-it/arxiv-search#43]
Author search for Smith; result #3 in our test cases has over 200 names listed.

Without the super long author lists, our new stuff looks GOOD on mobile!!

**Comment by erickpeirson** [comment]
Let's truncate at 30

**Comment by erickpeirson** [comment]
https://culibrary.atlassian.net/browse/ARXIVNG-306

**Comment by erickpeirson** [comment]
See also: ARXIVNG-307 - Remove institution from author display in search results
