### ISSUE TITLE
Error in sorting boxes under some conditions

### ISSUE THREAD

**Issue by eawoods** [cul-it/arxiv-search#51]
To reproduce:

1) Authors form: enter "cat*" in surname field (get list of 4 results)
2) Sort by: select Submitted date - descending, click Go
3) Get sent to Advanced Search page (instead of reordering results)

Possibly: pages with < 25 results don't reorder? Testing this hypothesis now.

**Comment by eawoods** [comment]
Update: the error only seems to occur on results from the authors page.

**Comment by erickpeirson** [comment]
https://culibrary.atlassian.net/browse/ARXIVNG-283

**Comment by erickpeirson** [comment]
@eawoods can you see if this is still happening in develop?

**Comment by eawoods** [comment]
will pull and check

**Comment by eawoods** [comment]
Thumbs up, now working as expected!!

**Comment by erickpeirson** [comment]
Woooo!!
