### ISSUE TITLE
In the search results, do we need the "Go" button?

### ISSUE THREAD

**Issue by jimentwood** [cul-it/arxiv-search#67]
I'm wondering if on the search results view if when you change the '# results per page' or 'sort results by' if it could automatically refresh the view rather than having to hit "Go".

![image](https://user-images.githubusercontent.com/11538356/36173152-fc7a999c-10d5-11e8-858b-76ce4ca5bec3.png)

**Comment by eawoods** [comment]
Something that came up today in my accessibility research: providing a "Go" button (or similar) is considered preferable from a standpoint of meeting Predictability accessibility guidelines.
I'm still learning more about this - was originally thinking the same, that auto-sort would be better, but if we decide not to keep the Go button I would like to describe a fully accessible alternative (not sure if there is one).

**Comment by erickpeirson** [comment]
Closing per usability requirements. Can revisit if we find a way to address usability issues.
