### ISSUE TITLE
Expand metadata field options

### ISSUE THREAD

**Issue by jimentwood** [cul-it/arxiv-search#68]
I frequently search by other metadata fields than Title, Author, Abstract. 
Can we include all the searchable fields in the advanced search?

![image](https://user-images.githubusercontent.com/11538356/36173296-8a6358f2-10d6-11e8-8ac5-9a492f6720e2.png)

**Comment by erickpeirson** [comment]
More can be added, we'd just have to think about normalization and how the query should be handled for each field.  Setting aside primary and submission date, this would be..

- DOI: Could be just a straight match to start?
- jref: Match on journal name?
- Secondary: Harder, might want to wait for a second version
- Comment: similar to abstract?

What else?

**Comment by erickpeirson** [comment]
![image](https://user-images.githubusercontent.com/3451594/36446482-661876a2-164f-11e8-9b4e-1afe6c8b5bc9.png)

**Comment by erickpeirson** [comment]
ARXIVNG-299 - Expose all* of the fields that we index in advanced search, barring some weird/problematic ones.

**Comment by jimentwood** [comment]
If any of the fields are considered *not* useful we could exclude them. After looking through this I could think of uses for most of them.

**Comment by erickpeirson** [comment]
@jimentwood Take a look at #81 ; does that look better?
