### ISSUE TITLE
Can we auto check Physics when a subcategory is selected in adv search?

### ISSUE THREAD

**Issue by jimentwood** [cul-it/arxiv-search#69]
On the advanced search, if a user selects one of the Physics sub archives can we automatically check the Physics box?

![image](https://user-images.githubusercontent.com/11538356/36173416-f08c12fe-10d6-11e8-8135-061432e9e01c.png)

**Comment by erickpeirson** [comment]
Yes. Should we also auto-check date options, eg specific year, when there is input to the corresponding field?

**Comment by eawoods** [comment]
The short answer to that question (should we auto check any field that has data entered) is yes from a UX perspective.
We chose to take a shortcut and not do the autochecking explicitly in this round because it would add ajax features that we weren't ready to support, if I recall correctly.

**Comment by erickpeirson** [comment]
ARXIVNG-298 - When user enters data in linked fields, their parent checkbox should be automatically checked.
