### ISSUE TITLE
Search paging does not show results at end of large query

### ISSUE THREAD

**Issue by rcplane** [cul-it/arxiv-search#70]
Click on last page link for everything in the last 12 months, fails to load

https://beta.arxiv.org/search/advanced?advanced=1&terms-0-term=&terms-0-operator=AND&terms-0-field=title&classification-physics_archives=all&date-past_12=y&date-year=2017&date-from_date=2018-01-01&date-to_date=2017-02-03&size=100&order=&start=162500

**Comment by mhl10** [comment]
This is related to #65

**Comment by erickpeirson** [comment]
I'm wondering to whether the ability to "go straight to page 247 of 638" is an actual requirement. How often would users do that anyway? My guess is that they would tend to look at the first few pages, probably in order. @eawoods what's your take from an UX perspective?

**Comment by eawoods** [comment]
From the UX perspective, steering results and better discovery/information seeking by refining queries has much higher value than supporting page results at any number. That much said, our system should do something gentler than breaking when one does try to click on a deep page...display a message with alternative suggestions for search, perhaps, or the "...and many more" suggestion made verbally the other day about long tail pagination.

Our current stats will probably bear out the guess that more than the first 5 pages are almost never looked at by a human being. We would do better to provide education for effective searching - messages and of course the fancier sort/facet/filter functionalities.

**Comment by erickpeirson** [comment]
ARXIVNG-297 - Pagination is broken for high-numbered pages
